In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'max_depth':[3,5,7,10,None],'min_samples_split':[2,5,10]}
grid = GridSearchCV( DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, Y_train)

re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

Fitting 5 folds for each of 15 candidates, totalling 75 fits
The R_score value for best parameter {'max_depth': 3, 'min_samples_split': 2}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024484,0.010413,0.011704,0.002640,3,2,"{'max_depth': 3, 'min_samples_split': 2}",0.861933,0.811635,0.824525,0.829739,0.794340,0.824434,0.022378,1
1,0.016599,0.003790,0.011127,0.002569,3,5,"{'max_depth': 3, 'min_samples_split': 5}",0.861933,0.811635,0.824525,0.829739,0.794340,0.824434,0.022378,1
2,0.016760,0.002138,0.010726,0.001747,3,10,"{'max_depth': 3, 'min_samples_split': 10}",0.861933,0.811635,0.824525,0.829739,0.794340,0.824434,0.022378,1
3,0.016716,0.001356,0.010835,0.001474,5,2,"{'max_depth': 5, 'min_samples_split': 2}",0.851752,0.765967,0.834946,0.772548,0.794971,0.804037,0.033927,4
4,0.018246,0.004747,0.011906,0.002784,5,5,"{'max_depth': 5, 'min_samples_split': 5}",0.851752,0.765967,0.834946,0.772548,0.794161,0.803875,0.033972,5
5,0.014785,0.001404,0.013859,0.004023,5,10,"{'max_depth': 5, 'min_samples_split': 10}",0.850433,0.765967,0.834946,0.772021,0.794788,0.803631,0.033666,6
6,0.017928,0.004599,0.014544,0.008981,7,2,"{'max_depth': 7, 'min_samples_split': 2}",0.831763,0.715673,0.792628,0.730185,0.752345,0.764519,0.042485,8
7,0.019171,0.006084,0.009531,0.001618,7,5,"{'max_depth': 7, 'min_samples_split': 5}",0.831329,0.709562,0.782614,0.737774,0.753560,0.762968,0.041557,9
8,0.016898,0.003420,0.009864,0.002597,7,10,"{'max_depth': 7, 'min_samples_split': 10}",0.829073,0.706414,0.812187,0.735933,0.763358,0.769393,0.045859,7
9,0.014148,0.002261,0.008520,0.002604,10,2,"{'max_depth': 10, 'min_samples_split': 2}",0.753140,0.622830,0.786491,0.646884,0.662169,0.694303,0.063797,14
10,0.011415,0.000719,0.007881,0.000951,10,5,"{'max_depth': 10, 'min_samples_split': 5}",0.741733,0.662158,0.769155,0.682444,0.717479,0.714594,0.038742,12
11,0.013433,0.002829,0.008264,0.003666,10,10,"{'max_depth': 10, 'min_samples_split': 10}",0.791716,0.672621,0.798231,0.698038,0.739471,0.740015,0.049732,10
12,0.013639,0.000491,0.007214,0.001634,None,2,"{'max_depth': None, 'min_samples_split': 2}",0.741759,0.566342,0.743462,0.623343,0.651400,0.665261,0.068850,15
13,0.013941,0.002259,0.005707,0.001060,None,5,"{'max_depth': None, 'min_samples_split': 5}",0.722572,0.623108,0.763949,0.664765,0.709624,0.696803,0.048568,13
14,0.009287,0.002287,0.006097,0.002618,None,10,"{'max_depth': None, 'min_samples_split': 10}",0.771742,0.639417,0.791564,0.691889,0.738118,0.726546,0.055130,11

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 29
BMI: 66
Children: 7
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[36538.85821818]

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(