In [3]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\dell\anaconda3\lib\site-packages (4.7.0)
Requirement already satisfied: narwhals>=1.15 in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (2.7.0)
Requirement already satisfied: numpy>=1.21.3 in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (1.16.3)

In [4]:
import pandas as pd
import lightgbm as lgb

In [5]:
dataset=pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [28]:
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor
param_grid = {'n_estimators':[50,100,200],'learning_rate':[0.01,0.1,0.3],'max_depth':[3,5,7]}
grid = GridSearchCV(LGBMRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, Y_train)

re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000294 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 313
[LightGBM] [Info] Number of data points in the train set: 936, number of used features: 5
[LightGBM] [Info] Start training from score 13232.916456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
The R_score value for best parameter {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}:

In [29]:
table=pd.DataFrame.from_dict(re)

In [30]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,5.250953,0.026225,0.009084,0.004375,0.01,3,50,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.559189,0.493084,0.532245,0.536780,0.492902,0.522840,0.026022,27
1,3.574211,2.455068,0.004861,0.000742,0.01,3,100,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.767294,0.685844,0.729103,0.738884,0.679200,0.720065,0.033189,24
2,0.928191,0.046178,0.004861,0.000326,0.01,3,200,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.868937,0.798363,0.829259,0.839452,0.780620,0.823326,0.031056,9
3,0.279398,0.006494,0.003912,0.000178,0.01,5,50,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.556771,0.490980,0.535930,0.542600,0.492521,0.523761,0.026993,25
4,0.490924,0.010780,0.004574,0.000452,0.01,5,100,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.764759,0.688913,0.730775,0.744856,0.679401,0.721741,0.032670,22
5,0.884433,0.011534,0.004942,0.000398,0.01,5,200,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.865444,0.797042,0.825434,0.837634,0.780915,0.821294,0.029840,10
6,0.249014,0.017376,0.003983,0.000185,0.01,7,50,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.557369,0.493133,0.533834,0.543180,0.491001,0.523703,0.026905,26
7,0.500278,0.008104,0.005041,0.001218,0.01,7,100,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.765796,0.692387,0.727969,0.743237,0.675849,0.721047,0.032885,23
8,1.046063,0.040837,0.005144,0.000308,0.01,7,200,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.866100,0.796061,0.822191,0.835298,0.777595,0.819449,0.030769,13
9,0.190425,0.006271,0.004056,0.000247,0.10,3,50,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.881928,0.825264,0.842786,0.851009,0.807845,0.841766,0.024990,1
10,0.429885,0.038880,0.004681,0.001234,0.10,3,100,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.877923,0.824627,0.839477,0.847190,0.803357,0.838515,0.024731,2
11,0.867468,0.018087,0.005055,0.000602,0.10,3,200,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.872138,0.813321,0.838328,0.841766,0.796345,0.832380,0.025946,5
12,0.270673,0.007868,0.003746,0.000087,0.10,5,50,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.877934,0.818823,0.833298,0.843539,0.799715,0.834662,0.026174,3
13,0.482634,0.010200,0.004711,0.000470,0.10,5,100,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.871717,0.806053,0.831899,0.836576,0.797129,0.828675,0.026200,7
14,0.679450,0.031997,0.008687,0.000975,0.10,5,200,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.865445,0.789887,0.829539,0.827164,0.783315,0.819070,0.029852,14
15,0.235476,0.047654,0.006625,0.000747,0.10,7,50,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.874887,0.814402,0.829497,0.840883,0.794572,0.830848,0.026938,6
16,0.441312,0.005618,0.007610,0.000859,0.10,7,100,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.866203,0.794982,0.826479,0.828992,0.787555,0.820842,0.028045,12
17,0.833322,0.051103,0.008218,0.000240,0.10,7,200,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.858261,0.777563,0.822991,0.812380,0.772658,0.808771,0.031441,17
18,0.094014,0.008183,0.006554,0.000425,0.30,3,50,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.873238,0.817008,0.834068,0.844588,0.798065,0.833393,0.025416,4
19,0.187265,0.015979,0.006637,0.000314,0.30,3,100,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.862969,0.805546,0.830078,0.838351,0.787338,0.824856,0.026239,8
20,0.412364,0.006234,0.007899,0.001159,0.30,3,200,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.854521,0.782976,0.828574,0.823922,0.775091,0.813017,0.029747,15
21,0.190206,0.011707,0.007023,0.000638,0.30,5,50,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.867023,0.797141,0.832923,0.831114,0.776924,0.821025,0.031223,11
22,0.304537,0.019888,0.006285,0.000727,0.30,5,100,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.858149,0.770347,0.827397,0.817535,0.760546,0.806795,0.036454,18
23,0.576708,0.036218,0.008033,0.000305,0.30,5,200,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.848550,0.746021,0.815224,0.793161,0.749109,0.790413,0.039191,20
24,0.217743,0.016696,0.006994,0.001161,0.30,7,50,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.853896,0.785850,0.821075,0.824929,0.779041,0.812958,0.027460,16
25,0.399265,0.010558,0.007063,0.000392,0.30,7,100,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.846137,0.757428,0.817329,0.805557,0.764444,0.798179,0.033226,19
26,0.549973,0.037695,0.008658,0.000722,0.30,7,200,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.834267,0.729812,0.804461,0.781070,0.746084,0.779139,0.037973,21

In [31]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 55
Children: 6
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [33]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[40612.18580211]

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(