In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'C':[0.1,1,10],'kernel':['rbf','linear']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, Y_train)

re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

Fitting 5 folds for each of 6 candidates, totalling 30 fits
The R_score value for best parameter {'C': 10, 'kernel': 'linear'}:

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.076791,0.007191,0.038487,0.002279,0.1,rbf,"{'C': 0.1, 'kernel': 'rbf'}",-0.041651,-0.037787,-0.148628,-0.138828,-0.142014,-0.101782,0.050787,4
1,0.086827,0.012632,0.016604,0.004425,0.1,linear,"{'C': 0.1, 'kernel': 'linear'}",-0.180846,0.011055,-0.237402,-0.251467,-0.166497,-0.165031,0.093773,6
2,0.076726,0.011693,0.036822,0.001751,1.0,rbf,"{'C': 1, 'kernel': 'rbf'}",-0.041843,-0.035206,-0.148244,-0.140044,-0.141968,-0.101461,0.051502,3
3,0.060379,0.005832,0.011394,0.000777,1.0,linear,"{'C': 1, 'kernel': 'linear'}",-0.198935,0.026229,-0.236356,-0.247440,-0.157780,-0.162857,0.099637,5
4,0.065584,0.001128,0.037291,0.001675,10.0,rbf,"{'C': 10, 'kernel': 'rbf'}",-0.045477,-0.013336,-0.151791,-0.151967,-0.139448,-0.100404,0.059028,2
5,0.058876,0.013238,0.006320,0.001111,10.0,linear,"{'C': 10, 'kernel': 'linear'}",-0.099849,0.109498,-0.136196,-0.141381,-0.075432,-0.068672,0.092313,1

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 34
BMI: 55
Children: 5
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[7111.99643253]

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(